spring:
  application:
    name: order-service
grpc:
  client:
    inventory:
      address: static://localhost:9090
      negotiationType: plaintext

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          add:
            type:
              headers: false