spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3307/order_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:

    consumer:

      group-id: order-group

      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer


      properties:

        spring.json.trusted.packages: "*"

        spring.json.use.type.headers: false


    producer:

      key-serializer:
        org.apache.kafka.common.serialization.StringSerializer

      value-serializer:
        org.springframework.kafka.support.serializer.JsonSerializer

      properties:

        spring.json.add.type.headers: false


grpc:
  client:
    inventory:
      address: static://localhost:9090
      negotiationType: plaintext

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true


server:
  port: 8083


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true


  retry:
    instances:
      inventoryService:
        maxAttempts: 3
        waitDuration: 2s

  timelimiter:
    instances:
      inventoryService:
        timeoutDuration: 5s


  bulkhead:
    instances:
      inventoryService:
        maxConcurrentCalls: 20
        maxWaitDuration: 1s


  ratelimiter:
    instances:
      inventoryService:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms