spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3307/inventory_db
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

grpc:
  server:
    port: 9090